# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Dec 12 10:57:37 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

import sys

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 355)
        MainWindow.setMinimumSize(QtCore.QSize(380, 355))
        MainWindow.setMaximumSize(QtCore.QSize(380, 355))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(280, 20, 81, 183))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.teamALabel = QtGui.QLabel(self.formLayoutWidget)
        self.teamALabel.setObjectName("teamALabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.teamALabel)
        self.teamALineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.teamALineEdit.setEnabled(False)
        self.teamALineEdit.setText("")
        self.teamALineEdit.setObjectName("teamALineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.teamALineEdit)
        self.teamBLabel = QtGui.QLabel(self.formLayoutWidget)
        self.teamBLabel.setObjectName("teamBLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.teamBLabel)
        self.teamBLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.teamBLineEdit.setEnabled(False)
        self.teamBLineEdit.setObjectName("teamBLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.teamBLineEdit)
        self.trumpLabel = QtGui.QLabel(self.formLayoutWidget)
        self.trumpLabel.setObjectName("trumpLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.trumpLabel)
        self.trumpLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.trumpLineEdit.setEnabled(False)
        self.trumpLineEdit.setObjectName("trumpLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.trumpLineEdit)
        self.leadLabel = QtGui.QLabel(self.formLayoutWidget)
        self.leadLabel.setObjectName("leadLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.leadLabel)
        self.leadLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.leadLineEdit.setEnabled(False)
        self.leadLineEdit.setObjectName("leadLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.leadLineEdit)
        self.leadLabel_2 = QtGui.QLabel(self.formLayoutWidget)
        self.leadLabel_2.setObjectName("leadLabel_2")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.leadLabel_2)
        self.leadLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.leadLineEdit_2.setEnabled(False)
        self.leadLineEdit_2.setObjectName("leadLineEdit_2")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.leadLineEdit_2)
        self.line = QtGui.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.line)
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 210, 171, 24))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.playerLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.playerLineEdit.setEnabled(False)
        self.playerLineEdit.setObjectName("playerLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.playerLineEdit)
        self.playerLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.playerLabel.setObjectName("playerLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.playerLabel)
        self.handCard1 = QtGui.QPushButton(self.centralwidget)
        self.handCard1.setGeometry(QtCore.QRect(10, 240, 81, 111))
        self.handCard1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mycard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.handCard1.setIcon(icon)
        self.handCard1.setIconSize(QtCore.QSize(97, 73))
        self.handCard1.setFlat(True)
        self.handCard1.setObjectName("handCard1")
        self.handCard2 = QtGui.QPushButton(self.centralwidget)
        self.handCard2.setGeometry(QtCore.QRect(80, 240, 81, 111))
        self.handCard2.setText("")
        self.handCard2.setIcon(icon)
        self.handCard2.setIconSize(QtCore.QSize(97, 73))
        self.handCard2.setFlat(True)
        self.handCard2.setObjectName("handCard2")
        self.handCard3 = QtGui.QPushButton(self.centralwidget)
        self.handCard3.setGeometry(QtCore.QRect(150, 240, 81, 111))
        self.handCard3.setText("")
        self.handCard3.setIcon(icon)
        self.handCard3.setIconSize(QtCore.QSize(97, 73))
        self.handCard3.setFlat(True)
        self.handCard3.setObjectName("handCard3")
        self.handCard4 = QtGui.QPushButton(self.centralwidget)
        self.handCard4.setGeometry(QtCore.QRect(220, 240, 81, 111))
        self.handCard4.setText("")
        self.handCard4.setIcon(icon)
        self.handCard4.setIconSize(QtCore.QSize(97, 73))
        self.handCard4.setFlat(True)
        self.handCard4.setObjectName("handCard4")
        self.handCard5 = QtGui.QPushButton(self.centralwidget)
        self.handCard5.setGeometry(QtCore.QRect(290, 240, 81, 111))
        self.handCard5.setText("")
        self.handCard5.setIcon(icon)
        self.handCard5.setIconSize(QtCore.QSize(97, 73))
        self.handCard5.setFlat(True)
        self.handCard5.setObjectName("handCard5")
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 0, 81, 111))
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(97, 73))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 50, 81, 111))
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(97, 73))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 100, 81, 111))
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(97, 73))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 50, 81, 111))
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(97, 73))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(192, 207, 91, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(277, 204, 91, 34))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Euchre", None, QtGui.QApplication.UnicodeUTF8))
        self.teamALabel.setText(QtGui.QApplication.translate("MainWindow", "Team A:", None, QtGui.QApplication.UnicodeUTF8))
        self.teamBLabel.setText(QtGui.QApplication.translate("MainWindow", "Team B:", None, QtGui.QApplication.UnicodeUTF8))
        self.trumpLabel.setText(QtGui.QApplication.translate("MainWindow", "Trick", None, QtGui.QApplication.UnicodeUTF8))
        self.leadLabel.setText(QtGui.QApplication.translate("MainWindow", "Trump:", None, QtGui.QApplication.UnicodeUTF8))
        self.leadLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Lead:", None, QtGui.QApplication.UnicodeUTF8))
        self.playerLabel.setText(QtGui.QApplication.translate("MainWindow", "Player:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))

class ControlMainWindow(QtGui.QMainWindow):
	def __init__(self, parent=None):
		super(ControlMainWindow, self).__init__(parent)
		self.ui =  Ui_MainWindow()
		self.ui.setupUi(self)
   
if __name__ == "__main__":
		app = QtGui.QApplication(sys.argv)
		mySW = ControlMainWindow()
		mySW.show()
		sys.exit(app.exec_())

